[package]
name = "smalux-core"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.49.0", features = ["default"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.149", features = ["default"] }
serde_json_path = { version = "0.7.2", features = ["default"] }
anyhow = { version = "1.0.100", features = ["default"] }
thiserror = { version = "2.0.18", features = ["default"] }
tracing = { version = "0.1.44", features = ["log", "std"] }
tracing-subscriber = { version = "0.3.22", features = ["env-filter", "json", "local-time"] }
tracing-appender = "0.2.5"
tracing-rolling-file = { version = "0.1.3", features = ["non-blocking"] }
reqwest = { version = "0.13.1", features = ["default", "rustls", "hickory-dns", "multipart"] }
hickory-resolver = { version = "0.25.2", features = ["default", "tokio"] }
