[package]
name = "smalux-protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { version = "1.0.100", features = ["default"] }
base64 = "0.22.1"
hkdf = "0.12.4"
sha2 = "0.10.9"
snow = "0.9.6"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
thiserror = { version = "2.0.18", features = ["default"] }
humantime-serde = "1.1.1"
smalux-core = { path = "../smalux-core" }
